project:
  type: website
  resources:
    - "pdf/*.pdf"
    
website:
  title: "    "
  site-url: https://mroberts1.github.io/digital-culture-sp24/
  # twitter-card:
  #   creator: "@mroberts_vma"
  #   card-style: summary_large_image
  favicon: "/img/cropped-cropped-flourish-1-270x270.gif"
  margin-header: |
    ![](/img/CollegeLockupStacked.jpg)
  navbar:
    background: "#62259d"
    search: true
    # left:
    #   - text: Home
    #     file: index.qmd
    #   - text: Syllabus
    #     file: syllabus.qmd
    #   - text: Pages
    #     menu: 
    #       - text: Generating SVGs
    #         file: mecha.qmd
    #       - text: IRC Quickstart
    #         file: resources/irc-quickstart.qmd
    #       - text: Mastodon Quickstart
    #         file: resources/mastodon-quickstart.qmd
    right:
      - icon: envelope
        aria-label: envelope
        href: mailto:martin_roberts@emerson.edu
      - icon: mastodon
        aria-label: mastodon
        href: https://merveilles.town/@dokoissho
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1
      - icon: facebook
        aria-label: facebook
        href: https://facebook.com/mr05301
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mroberts_VMA
  page-footer:
    left: "Martin Roberts | Updated: 8 January 2025"

format: 
  html: 
    toc: true
    toc-depth: 2
    toc-location: left
    toc-title: 'Curriculum Vitae'
    self-contained: true
    grid: 
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 2em
      body-width: 600px
    theme: ember.scss
    css: custom.scss
    linestretch: 1.5
    fontsize: 0.9em
    smooth-scroll: true
    linkcolor: "black"
    ink-external-newwindow: true
    #reader-mode: true
  PrettyPDF-pdf: default
